name: Run Python ETL Scripts

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest' # Specify the version of gcloud you want to use
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} # Ensure this secret is set in your GitHub repository
        project_id: ${{ secrets.GCP_PROJECT_ID }} # Ensure this secret is set in your GitHub repository
        export_default_credentials: true # Exports the credentials to the environment for use in your scripts

    - name: Authenticate with Google Cloud
      # Authenticates with Google Cloud using the service account key.
      # This step is necessary if your scripts interact with Google Cloud services.
      run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    - name: Set up Python
      # Sets up a Python environment on the runner.
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Specify the Python version you are using (e.g., '3.9', '3.10', '3.11')

    - name: Install dependencies
      # Installs all Python packages listed in your requirements.txt file.
      # Assumes requirements.txt is in the root of your repository or the 'trendyol-etl' directory.
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Adjust path if requirements.txt is elsewhere

    - name: Run orders.py
      # Executes the orders.py script.
      # Environment variables are passed securely using GitHub Secrets.
      # Ensure these secrets are configured in your GitHub repository settings.
      env:
        TRENDYOL_API_TOKEN: ${{ secrets.TRENDYOL_API_TOKEN }}
        TRENDYOL_SUPPLIER_ID: ${{ secrets.TRENDYOL_SUPPLIER_ID }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} # Still needed if your script uses os.getenv directly
      run: python orders.py

    - name: Run products.py
      # Executes the products.py script.
      env:
        TRENDYOL_API_TOKEN: ${{ secrets.TRENDYOL_API_TOKEN }}
        TRENDYOL_SUPPLIER_ID: ${{ secrets.TRENDYOL_SUPPLIER_ID }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: python products.py

    - name: Run settlements.py
      # Executes the settlements.py script.
      env:
        TRENDYOL_API_TOKEN: ${{ secrets.TRENDYOL_API_TOKEN }}
        TRENDYOL_SUPPLIER_ID: ${{ secrets.TRENDYOL_SUPPLIER_ID }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: python settlements.py

    - name: Run otherfinancials.py
      # Executes the otherfinancials.py script.
      env:
        TRENDYOL_API_TOKEN: ${{ secrets.TRENDYOL_API_TOKEN }}
        TRENDYOL_SUPPLIER_ID: ${{ secrets.TRENDYOL_SUPPLIER_ID }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: python otherfinancials.py
