name: Run Python ETL Scripts

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run all ETL Scripts
      env:
        TRENDYOL_API_TOKEN: ${{ secrets.TRENDYOL_API_TOKEN }}
        TRENDYOL_SUPPLIER_ID: ${{ secrets.TRENDYOL_SUPPLIER_ID }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        BIGQUERY_LOCATION: ${{ secrets.BIGQUERY_LOCATION }}
        BIGQUERY_PROJECT_ID: ${{ secrets.BIGQUERY_PROJECT_ID }}
        BIGQUERY_DATASET_ID: ${{ secrets.BIGQUERY_DATASET_ID }}
      run: |
        python orders.py
        python products.py
        python settlements.py
        python otherfinancials.py